added lgpd-odb-latest.yml

diff --git a/lgpd-odb-latest.yml b/lgpd-odb-latest.yml
--- a/lgpd-odb-latest.yml
+++ b/lgpd-odb-latest.yml
@@ -13,59 +13,59 @@ services:
 
 
 
-  elasticsearch:
-    image: "elasticsearch:6.7.2"
-    domainname: pontus-demo.com
-    ports:
-      - "9200:9200"
-      - "9300:9300"
-    restart: on-failure
-    privileged: false
-    hostname: elasticsearch
-    container_name: elasticsearch.pontus-demo.com
-    environment:
-      - node.name=elasticsearch
-      - discovery.type=single-node
-      - cluster.name=docker-cluster
-      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
-    networks:
-      pontusvision:
-        ipv4_address: 172.28.1.2
-    ulimits:
-      memlock:
-        soft: -1
-        hard: -1
-
+#  elasticsearch:
+#    image: "elasticsearch:6.7.2"
+#    domainname: pontus-demo.com
+#    ports:
+#      - "9200:9200"
+#      - "9300:9300"
+#    restart: on-failure
+#    privileged: false
+#    hostname: elasticsearch
+#    container_name: elasticsearch.pontus-demo.com
+#    environment:
+#      - node.name=elasticsearch
+#      - discovery.type=single-node
+#      - cluster.name=docker-cluster
+#      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
+#    networks:
+#      pontusvision:
+#        ipv4_address: 172.28.1.2
+#    ulimits:
+#      memlock:
+#        soft: -1
+#        hard: -1
+#
 
   graphdb-nifi:
-    image: "pontusvisiongdpr/pontus-track-graphdb-nifi-pt:latest"
+    image: "pontusvisiongdpr/pontus-track-graphdb-odb-pt:latest"
     domainname: pontus-demo.com
     ports:
       - "8182:8183"
       - "8183:8183"
       - "7000:7000"
       - "3001:3001"
-      - "5009:5009"
+      - "5009:5007"
     restart: on-failure
     privileged: false
     hostname: graphdb-nifi
     container_name: graphdb-nifi.pontus-demo.com
     secrets:
       - MAPPING_SALESFORCE_GRAPH
-    depends_on:
-      - elasticsearch
+    #depends_on:
+      #- elasticsearch
     networks:
       pontusvision:
         ipv4_address: 172.28.1.3
     command: >
       /bin/bash -c "
-        echo Waiting for elasticsearch service start...;
-        while ! nc -z elasticsearch 9200;
-        do
-          sleep 1;
-        done;
+        #echo Waiting for elasticsearch service start...;
+        #while ! nc -z elasticsearch 9200;
+        #do
+          #sleep 1;
+        #done;
         echo Connected!;
-        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp /opt/pontus-graphdb/graphdb-current/bin/pv-gdpr-graphdb.sh /opt/pontus-graphdb/graphdb-current/conf/gremlin-server-nifi.yml
+        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp /orientdb/bin/server.sh 
       "
 
 
